blank_issues_enabled: false
issue_template:
  - bug_report.md
  - feature_request.md
contact_links:
  - name: Reportar Problema Geral
    url: https://github.com/Logika-Sciuro/.github/issues
    about: Utilize este link para relatar problemas gerais ou dúvidas administrativas no nível da organização.